version: "3"

services:
  sonarqube:
    image: sonarqube:7.9.6
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar_pass
      - sonar.jdbc.url=jdbc:postgresql://db/sonar

    volumes:
      - ./volumes/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./volumes/sonarqube/sonarqube_logs:/opt/sonarqube/logs

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar_pass
    volumes:
      - ./volumes/postgresql/postgresql:/var/lib/postgresql
      - ./volumes/postgresql/postgresql_data:/var/lib/postgresql/data
